// ConstantData.js
export const shiftLeadsData = {
  Owens: [
    "Kayla Agnew",
    "Brady Anderton",
    "Riley Henze",
    "Clay O'Dell",
    "Jonathan McAteer",
  ],
  University: [
    "Andrew Christensen",
    "Megan Davis",
    "Marlee Samuel",
    "Sage Simpson",
    "Rayne Swiger",
    "Megan Skoko",
    "Lillian Teer",
  ],
};

export const broistasData = {
  Owens: [
    "Kayla Agnew",
    "Brady Anderton",
    "Riley Henze",
    "Clay O'Dell",
    "Anne Kusserow",
    "Emily Haney",
    "Gerrit Rempfer",
    "Grace Chambers",
    "Ivy Ames",
    "Jonathan McAteer",
    "Katie Chen",
    "Kiana Rayas",
    "Laura Morgan",
    "Lauren Saint",
    "Mikayla Sotelo",
    "Stella Foreman",
    "Kai Lockhart",
  ],
  University: [
    "Andrew Christensen",
    "Megan Davis",
    "Marlee Samuel",
    "Sage Simpson",
    "Rayne Swiger",
    "Megan Skoko",
    "Lillian Teer",
    "Brooklyn Lazenby",
    "Carley White",
    "Clayton Thole",
    "Declan Montgomery",
    "Emily Kiengkham",
    "Jada Chiu",
    "Lauren Sithole",
    "Lydia Sitlinger",
    "Reginae Gary",
    "Sydnii Arthur",
    "Faith Pouliot",
  ],
};

export const storeHours = [
  "5:00 AM",
  "5:15 AM",
  "5:30 AM",
  "5:45 AM",
  "6:00 AM",
  "6:15 AM",
  "6:30 AM",
  "6:45 AM",
  "7:00 AM",
  "7:15 AM",
  "7:30 AM",
  "7:45 AM",
  "8:00 AM",
  "8:15 AM",
  "8:30 AM",
  "8:45 AM",
  "9:00 AM",
  "9:15 AM",
  "9:30 AM",
  "9:45 AM",
  "10:00 AM",
  "10:15 AM",
  "10:30 AM",
  "10:45 AM",
  "11:00 AM",
  "11:15 AM",
  "11:30 AM",
  "11:45 AM",
  "12:00 PM",
  "12:15 PM",
  "12:30 PM",
  "12:45 PM",
  "1:00 PM",
  "1:15 PM",
  "1:30 PM",
  "1:45 PM",
  "2:00 PM",
  "2:15 PM",
  "2:30 PM",
  "2:45 PM",
  "3:00 PM",
  "3:15 PM",
  "3:30 PM",
  "3:45 PM",
  "4:00 PM",
  "4:15 PM",
  "4:30 PM",
  "4:45 PM",
  "5:00 PM",
  "5:15 PM",
  "5:30 PM",
  "5:45 PM",
  "6:00 PM",
  "6:15 PM",
  "6:30 PM",
  "6:45 PM",
  "7:00 PM",
  "7:15 PM",
  "7:30 PM",
  "7:45 PM",
  "8:00 PM",
  "8:15 PM",
  "8:30 PM",
  "8:45 PM",
  "9:00 PM",
  "9:15 PM",
  "9:30 PM",
  "9:45 PM",
  "10:00 PM",
  "10:15 PM",
  "10:30 PM",
  "10:45 PM",
  "11:00 PM",
  "11:15 PM",
  "11:30 PM",
  "11:45 PM",
];


export const positions = [
  { position: "Drive Shots" },
  { position: "Line Buster 1" },
  { position: "Drive Milk" },
  { position: "Walk Up Shots" },
  { position: "Walk Up Milk" },
  { position: "Window" },
  { position: "Line Buster 2" },
  { position: "Pit 1" },
  { position: "Side Bar Shots" },
  { position: "Line Buster 3" },
  { position: "Side Bar Milk" },
  { position: "Pit 2" },
  { position: "Drink Runner" },
  { position: "Flow Master" },
  { position: "Walk Up Window" },
];

export const shiftLengths = [
  { value: 0.5, label: "30 minutes" },
  { value: 1, label: "1 hour" },
  { value: 1.5, label: "1 hour 30 minutes" },
  { value: 2, label: "2 hours" },
  { value: 2.5, label: "2 hours 30 minutes" },
  { value: 3, label: "3 hours" },
  { value: 3.5, label: "3 hours 30 minutes" },
  { value: 4, label: "4 hours" },
  { value: 4.5, label: "4 hours 30 minutes" },
  { value: 5, label: "5 hours" },
  { value: 5.5, label: "5 hours 30 minutes" },
  { value: 6, label: "6 hours" },
  { value: 6.5, label: "6 hours 30 minutes" },
  { value: 7, label: "7 hours" },
  { value: 7.5, label: "7 hours 30 minutes" },
  { value: 8, label: "8 hours" },
];

export const shiftTypeLineupHours = [
  {
    shiftType: "Morning",
    times: [
      "4:45 AM",
      "5:00 AM",
      "6:00 AM",
      "7:00 AM",
      "8:00 AM",
      "9:00 AM",
      "10:00 AM",
      "11:00 AM",
    ],
  },
  {
    shiftType: "Mid",
    times: [
      "11:00 AM",
      "12:00 PM",
      "1:00 PM",
      "2:00 PM",
      "3:00 PM",
      "4:00 PM",
      "5:00 PM",
    ],
  },
  {
    shiftType: "Night",
    times: [
      "5:00 PM",
      "6:00 PM",
      "7:00 PM",
      "8:00 PM",
      "9:00 PM",
      "10:00 PM",
      "11:00 PM",
    ],
  },
];
